### PR TITLE
RL benchmarks

### PR DESCRIPTION
**Pull request by cabrerac**
Adding the proposal for the RL benchmarks project.

### CODE REVIEW

**Comment by cabrerac** [comment]
Hi Neil, a reminder on this PR.

Thanks,
Christian

**Comment by lawrennd** [comment]
Thanks for the bump!

**Comment by lawrennd** [comment]
Just quickly tagging @pierthodo as I know he is keen on setting up benchmarks ... Pierre ... is this overlapping with your vision?

**Comment by pierthodo** [comment]
Im definitely interested in this type of benchmark and happy to help any way I can.

**Comment by lawrennd** [comment]
Shall we add both of your names as supervisors?

**Comment by cabrerac** [comment]
Happy if we co-supervise it!

I added Pierre as supervisor.

**Review by lawrennd — APPROVED** [review]

**Pull request merged**
